"""
The package root's public surface.

``ROOT_SURFACE`` is the checked-in snapshot of ``launchdarkly_ai_server.__all__``
(TESTING.md §0.3). It is spelled out so that any change to the root, including
an experimental name leaking onto it, fails here and is seen in review. Update
it deliberately, in the same change that adds or removes a root export.
"""

from __future__ import annotations

ROOT_SURFACE = frozenset(
    {
        "AIConfig",
        "AiConfigRep",
        "ConfigInstance",
        "ConversationIdSpanProcessor",
        "Criterion",
        "DatasetRow",
        "EvalRunResult",
        "EvaluationsError",
        "EvaluationsModule",
        "ExecuteStreamDoneEvent",
        "ExecuteStreamEvent",
        "GenerationConfig",
        "GraphArgs",
        "GraphDefinition",
        "GraphEdge",
        "GraphInstance",
        "GraphNode",
        "GraphOptions",
        "GraphStreamEvent",
        "GraphTopology",
        "HandlerResult",
        "HandlerStreamEvent",
        "InitClientOptions",
        "InputTokenDetails",
        "Judge",
        "JudgeResult",
        "JudgeRunResult",
        "JudgeTask",
        "LDClientInterface",
        "LDContext",
        "Message",
        "NATIVE_TOOL_KEY",
        "NativeTool",
        "ParseFailure",
        "ParseResult",
        "ParseSuccess",
        "ProviderGraphResponse",
        "ProviderHandler",
        "ProviderResponse",
        "Registry",
        "RunSummary",
        "RunUsage",
        "SDK_INFO_CONTEXT",
        "SDK_INFO_EVENT",
        "Scorer",
        "SpanMessage",
        "SpanMessagePart",
        "SpanUsage",
        "StreamChunkEvent",
        "StreamDoneEvent",
        "StreamEvent",
        "ToolDefinitionInput",
        "TrackData",
        "UsageDict",
        "VariationMeta",
        "add_cached_tokens_to_input",
        "any_multimodal",
        "build_judge_tasks",
        "compose",
        "compose_history",
        "config",
        "content_to_text",
        "conversation_id",
        "create_handler",
        "create_run_usage",
        "end_span_once",
        "end_unfinished_spans",
        "execute_and_stream",
        "execute_and_track",
        "extract_variation",
        "get_client",
        "global_registry",
        "graph",
        "has_multimodal_content",
        "image_block_to_url",
        "init_client",
        "init_evaluations",
        "inspect_config",
        "is_content_blocks",
        "lang_chain_content_text",
        "lang_chain_finish_reasons",
        "lang_chain_span_messages",
        "lang_chain_span_usage",
        "make_track_data",
        "model_stamps_from_meta",
        "normalize_mode",
        "number_or_zero",
        "omit_model_stamps",
        "parse_ai_config",
        "parse_json_with_possible_fences",
        "parse_template",
        "parse_usage",
        "register_ai_sdk_package",
        "resolve_graph",
        "resolve_handlers",
        "resolve_tools",
        "run_judge",
        "run_judges",
        "set_conversation_id_if_absent",
        "set_input_content_attributes",
        "set_ld_span_attributes",
        "set_model_identity_attributes",
        "set_openllmetry_completion",
        "set_openllmetry_prompt",
        "set_output_content_attributes",
        "set_tool_call_content_attributes",
        "set_tool_definition_attributes",
        "set_usage_span_attributes",
        "shutdown",
        "text_message",
        "to_ld_context",
        "to_semconv_finish_reason",
        "to_usage_dict",
        "wrap_tool_handlers",
    }
)


def test_root_surface_is_exactly_the_snapshot() -> None:
    import launchdarkly_ai_server as package

    assert set(package.__all__) == ROOT_SURFACE
    assert len(package.__all__) == len(ROOT_SURFACE), "duplicate name in __all__"
    for name in ROOT_SURFACE:
        assert hasattr(package, name), name
