"""LaunchDarkly AI SDK - core client for Python."""

__version__ = "0.1.3"  # x-release-please-version

from .client import ConfigInstance, config
from .content import (
    SpanMessage,
    SpanMessagePart,
    ToolDefinitionInput,
    lang_chain_finish_reasons,
    lang_chain_span_messages,
    set_input_content_attributes,
    set_output_content_attributes,
    set_tool_call_content_attributes,
    set_tool_definition_attributes,
    text_message,
    to_semconv_finish_reason,
)
from .conversation import (
    ConversationIdSpanProcessor,
    conversation_id,
    set_conversation_id_if_absent,
)
from .graph import GraphInstance, graph, resolve_graph
from .judges import build_judge_tasks, run_judge, run_judges
from .lifecycle import (
    extract_variation,
    get_client,
    init_client,
    inspect_config,
    shutdown,
)
from .registry import (
    Registry,
    compose,
    global_registry,
    resolve_handlers,
    resolve_tools,
)
from .skills import (
    InMemorySkillStore,
    all_skills,
    get_skill,
    get_skill_result,
    get_skills,
    skill_refs,
)
from .skills_core import SkillStore
from .skills_fdv2 import FDv2SkillStore, StoreDiagnostics
from .skills_fs import (
    MANIFEST_FILENAME,
    MANIFEST_VERSION,
    SKILL_FILENAME,
    OnUnavailable,
    write_skills,
)
from .skills_watch import SkillWatcher, watch_skills
from .tracking import execute_and_stream, execute_and_track, wrap_tool_handlers
from .types import (
    NATIVE_TOOL_KEY,
    AiConfigRep,
    ExecuteStreamDoneEvent,
    ExecuteStreamEvent,
    GraphArgs,
    GraphDefinition,
    GraphEdge,
    GraphNode,
    GraphOptions,
    GraphTopology,
    HandlerResult,
    HandlerStreamEvent,
    InitClientOptions,
    InputTokenDetails,
    JudgeResult,
    JudgeRunResult,
    JudgeTask,
    LDClientInterface,
    LDContext,
    Message,
    NativeTool,
    ParseFailure,
    ParseResult,
    ParseSuccess,
    ProviderGraphResponse,
    ProviderHandler,
    ProviderResponse,
    ReconcileAction,
    ReconcileActionKind,
    ReconcileReport,
    Skill,
    SkillOutcome,
    SkillOutcomeReason,
    SkillReference,
    StreamChunkEvent,
    StreamDoneEvent,
    StreamEvent,
    TrackData,
    UsageDict,
    VariationMeta,
)
from .types_validation import parse_ai_config
from .utils import (
    RunUsage,
    SpanUsage,
    add_cached_tokens_to_input,
    create_handler,
    create_run_usage,
    end_span_once,
    end_unfinished_spans,
    lang_chain_span_usage,
    make_track_data,
    normalize_mode,
    number_or_zero,
    parse_json_with_possible_fences,
    parse_template,
    parse_usage,
    set_ld_span_attributes,
    set_model_identity_attributes,
    set_openllmetry_completion,
    set_openllmetry_prompt,
    set_usage_span_attributes,
    to_ld_context,
    to_usage_dict,
)

__all__ = [  # noqa: RUF022
    # types
    "NATIVE_TOOL_KEY",
    "AiConfigRep",
    "ExecuteStreamDoneEvent",
    "ExecuteStreamEvent",
    "GraphArgs",
    "GraphDefinition",
    "GraphEdge",
    "GraphNode",
    "GraphOptions",
    "GraphTopology",
    "HandlerResult",
    "HandlerStreamEvent",
    "InitClientOptions",
    "JudgeResult",
    "JudgeRunResult",
    "JudgeTask",
    "LDClientInterface",
    "LDContext",
    "Message",
    "NativeTool",
    "ParseFailure",
    "ParseResult",
    "ParseSuccess",
    "ProviderGraphResponse",
    "ProviderHandler",
    "ProviderResponse",
    "ReconcileAction",
    "ReconcileActionKind",
    "ReconcileReport",
    "Skill",
    "SkillOutcome",
    "SkillReference",
    "StreamChunkEvent",
    "StreamDoneEvent",
    "StreamEvent",
    "TrackData",
    "InputTokenDetails",
    "RunUsage",
    "SpanMessage",
    "SpanMessagePart",
    "SpanUsage",
    "ToolDefinitionInput",
    "UsageDict",
    "add_cached_tokens_to_input",
    "create_run_usage",
    "end_span_once",
    "end_unfinished_spans",
    "lang_chain_finish_reasons",
    "lang_chain_span_messages",
    "lang_chain_span_usage",
    "number_or_zero",
    "set_input_content_attributes",
    "set_model_identity_attributes",
    "set_output_content_attributes",
    "set_tool_call_content_attributes",
    "set_tool_definition_attributes",
    "set_usage_span_attributes",
    "to_usage_dict",
    "text_message",
    "to_semconv_finish_reason",
    "VariationMeta",
    # utils
    "create_handler",
    "make_track_data",
    "normalize_mode",
    "parse_json_with_possible_fences",
    "parse_template",
    "parse_usage",
    "set_ld_span_attributes",
    "set_openllmetry_completion",
    "set_openllmetry_prompt",
    "to_ld_context",
    # validation
    "parse_ai_config",
    # registry
    "Registry",
    "compose",
    "resolve_handlers",
    "resolve_tools",
    "global_registry",
    # tracking
    "wrap_tool_handlers",
    "execute_and_track",
    "execute_and_stream",
    # lifecycle
    "init_client",
    "get_client",
    "shutdown",
    "extract_variation",
    "inspect_config",
    # judges
    "build_judge_tasks",
    "run_judge",
    "run_judges",
    # client
    "config",
    "ConfigInstance",
    # conversation
    "ConversationIdSpanProcessor",
    "conversation_id",
    "set_conversation_id_if_absent",
    # graph
    "graph",
    "resolve_graph",
    "GraphInstance",
    # skills
    "skill_refs",
    "get_skill",
    "get_skill_result",
    "get_skills",
    "all_skills",
    "write_skills",
    "SkillStore",
    "InMemorySkillStore",
    # skills — the FDv2 delivery transport, and the eager re-reconcile it enables
    "FDv2SkillStore",
    "StoreDiagnostics",
    "watch_skills",
    "SkillWatcher",
    # skills — the three closed-set unions a typed consumer needs to name
    "ReconcileActionKind",
    "OnUnavailable",
    "SkillOutcomeReason",
    # skills — on-disk constants, identical across languages
    "SKILL_FILENAME",
    "MANIFEST_FILENAME",
    "MANIFEST_VERSION",
]
