__version__ = "0.1.1"  # x-release-please-version

from .client import ConfigInstance, config
from .graph import GraphInstance, graph, resolve_graph
from .judges import build_judge_tasks, run_judge, run_judges
from .lifecycle import (
    extract_variation,
    get_client,
    init_client,
    inspect_config,
    shutdown,
)
from .registry import (
    Registry,
    compose,
    global_registry,
    resolve_handlers,
    resolve_tools,
)
from .tracking import execute_and_stream, execute_and_track, wrap_tool_handlers
from .types import (
    NATIVE_TOOL_KEY,
    AiConfigRep,
    ExecuteStreamDoneEvent,
    ExecuteStreamEvent,
    GraphArgs,
    GraphDefinition,
    GraphEdge,
    GraphNode,
    GraphOptions,
    GraphTopology,
    HandlerResult,
    HandlerStreamEvent,
    InitClientOptions,
    JudgeResult,
    JudgeRunResult,
    JudgeTask,
    LDClientInterface,
    LDContext,
    Message,
    NativeTool,
    ParseFailure,
    ParseResult,
    ParseSuccess,
    ProviderGraphResponse,
    ProviderHandler,
    ProviderResponse,
    StreamChunkEvent,
    StreamDoneEvent,
    StreamEvent,
    TrackData,
    UsageDict,
    VariationMeta,
)
from .types_validation import parse_ai_config
from .utils import (
    create_handler,
    make_track_data,
    normalize_mode,
    parse_json_with_possible_fences,
    parse_template,
    parse_usage,
    set_ld_span_attributes,
    set_openllmetry_completion,
    set_openllmetry_prompt,
    to_ld_context,
)

__all__ = [  # noqa: RUF022
    # types
    "NATIVE_TOOL_KEY",
    "AiConfigRep",
    "ExecuteStreamDoneEvent",
    "ExecuteStreamEvent",
    "GraphArgs",
    "GraphDefinition",
    "GraphEdge",
    "GraphNode",
    "GraphOptions",
    "GraphTopology",
    "HandlerResult",
    "HandlerStreamEvent",
    "InitClientOptions",
    "JudgeResult",
    "JudgeRunResult",
    "JudgeTask",
    "LDClientInterface",
    "LDContext",
    "Message",
    "NativeTool",
    "ParseFailure",
    "ParseResult",
    "ParseSuccess",
    "ProviderGraphResponse",
    "ProviderHandler",
    "ProviderResponse",
    "StreamChunkEvent",
    "StreamDoneEvent",
    "StreamEvent",
    "TrackData",
    "UsageDict",
    "VariationMeta",
    # utils
    "create_handler",
    "make_track_data",
    "normalize_mode",
    "parse_json_with_possible_fences",
    "parse_template",
    "parse_usage",
    "set_ld_span_attributes",
    "set_openllmetry_completion",
    "set_openllmetry_prompt",
    "to_ld_context",
    # validation
    "parse_ai_config",
    # registry
    "Registry",
    "compose",
    "resolve_handlers",
    "resolve_tools",
    "global_registry",
    # tracking
    "wrap_tool_handlers",
    "execute_and_track",
    "execute_and_stream",
    # lifecycle
    "init_client",
    "get_client",
    "shutdown",
    "extract_variation",
    "inspect_config",
    # judges
    "build_judge_tasks",
    "run_judge",
    "run_judges",
    # client
    "config",
    "ConfigInstance",
    # graph
    "graph",
    "resolve_graph",
    "GraphInstance",
]
